import Editor from './editor';
import AutoResize from './plugins/autoResize';
import BlockCodeBlock from './plugins/block/code-block';
import BlockCodeInline from './plugins/block/code-inline';
import BlockQuote from './plugins/block/quote';
import BlockWrap from './plugins/block/wrap';
import Clear from './plugins/clear';
import FontBold from './plugins/font/bold';
import FontItalic from './plugins/font/italic';
import FontStrikethrough from './plugins/font/strikethrough';
import FontUnderline from './plugins/font/underline';
import FullScreen from './plugins/fullScreen';
import Header from './plugins/header';
import Image from './plugins/Image';
import Link from './plugins/link';
import ListOrdered from './plugins/list/ordered';
import ListUnordered from './plugins/list/unordered';
import Logger from './plugins/logger';
import ModeToggle from './plugins/modeToggle';
import Table from './plugins/table';
import TabInsert from './plugins/tabInsert';
import { PluginComponent } from './plugins/Plugin';
import type { PluginProps } from './plugins/Plugin';
import DropList from './components/DropList/index';
export { DropList };
export { PluginComponent };
export type { PluginProps };
export { default as getDecorated } from './utils/decorate';
export declare const Plugins: {
    Header: typeof Header;
    FontBold: typeof FontBold;
    FontItalic: typeof FontItalic;
    FontUnderline: typeof FontUnderline;
    FontStrikethrough: typeof FontStrikethrough;
    ListUnordered: typeof ListUnordered;
    ListOrdered: typeof ListOrdered;
    BlockQuote: typeof BlockQuote;
    BlockWrap: typeof BlockWrap;
    BlockCodeInline: typeof BlockCodeInline;
    BlockCodeBlock: typeof BlockCodeBlock;
    Table: typeof Table;
    Image: typeof Image;
    Link: typeof Link;
    Clear: typeof Clear;
    Logger: typeof Logger;
    ModeToggle: typeof ModeToggle;
    FullScreen: typeof FullScreen;
    AutoResize: typeof AutoResize;
    TabInsert: typeof TabInsert;
};
export default Editor;
